package com.tgassistant.bot.command;

import java.util.List;

import com.tgassistant.bot.command.action.AddAction;
import com.tgassistant.bot.command.action.ClearAction;
import com.tgassistant.bot.command.action.ClearConfirmedAction;
import com.tgassistant.bot.command.action.DeleteAction;
import com.tgassistant.bot.command.action.TaskAction;
import com.tgassistant.bot.command.action.ViewAction;
import com.tgassistant.domain.Task;
import com.tgassistant.domain.TaskType;
import com.tgassistant.service.TaskService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class TaskTypeCommandTest {

    @Mock
    private TaskService taskService;

    @Captor
    private ArgumentCaptor<List<String>> descriptionsCaptor;

    private final PendingInputStore pendingInput = new PendingInputStore();

    private static CommandRequest request(String arguments) {
        return new CommandRequest("/day", arguments, 42L);
    }

    private TaskTypeCommand daily() {
        return new DailyTaskCommand(taskService, actions());
    }

    private TaskTypeCommand weekly() {
        return new WeeklyTaskCommand(taskService, actions());
    }

    /**
     * The real actions in the order Spring's {@code @Order} gives them, so these tests cover
     * the wiring between command and actions rather than a stand-in for it.
     */
    private List<TaskAction> actions() {
        ClearConfirmedAction clearConfirmed = new ClearConfirmedAction();
        return List.of(new ViewAction(), new AddAction(pendingInput), new DeleteAction(),
                new ClearAction(clearConfirmed), clearConfirmed);
    }

    private static Task task(long id, String description) {
        Task task = new Task(description, TaskType.DAILY);
        // The id is generated by JPA, so tests have to plant it to build delete buttons.
        ReflectionTestUtils.setField(task, "id", id);
        return task;
    }

    // --- the menu reached by tapping "Daily tasks" -----------------------------------------

    @Test
    void offersTheFourActionsWhenTappedFromTheMenu() {
        CommandReply reply = daily().execute(request(""));

        assertThat(reply.text()).isEqualTo("Daily tasks — what do you want to do?");
        assertThat(reply.buttons()).containsExactly(
                new ReplyButton("View", "/day :view"),
                new ReplyButton("Add", "/day :add"),
                new ReplyButton("Delete", "/day :delete"),
                new ReplyButton("Delete all", "/day :clear"));
        verifyNoInteractions(taskService);
    }

    // --- adding, which is still what free text does -----------------------------------------

    @Test
    void storesCommaSeparatedDescriptionsAsDailyTasks() {
        CommandReply reply = daily().execute(request("buy milk, walk the dog ,  call mom"));

        verify(taskService).addTasks(descriptionsCaptor.capture(), eq(TaskType.DAILY));
        assertThat(descriptionsCaptor.getValue()).containsExactly("buy milk", "walk the dog", "call mom");
        assertThat(reply.text()).isEqualTo("Added 3 daily tasks:\n- buy milk\n- walk the dog\n- call mom");
    }

    @Test
    void storesSingleDescriptionAsWeeklyTask() {
        CommandReply reply = weekly().execute(new CommandRequest("/week", "finish the report", 42L));

        verify(taskService).addTasks(List.of("finish the report"), TaskType.WEEKLY);
        assertThat(reply.text()).isEqualTo("Added 1 weekly task:\n- finish the report");
    }

    /**
     * Actions are marked with ':' precisely so a description can never be mistaken for one.
     */
    @Test
    void treatsAnActionWordWithoutTheMarkerAsATaskDescription() {
        CommandReply reply = daily().execute(request("view"));

        verify(taskService).addTasks(List.of("view"), TaskType.DAILY);
        assertThat(reply.text()).isEqualTo("Added 1 daily task:\n- view");
    }

    @Test
    void labelsItselfReadably() {
        assertThat(daily().label()).isEqualTo("Daily tasks");
        assertThat(weekly().label()).isEqualTo("Weekly tasks");
    }

    /**
     * The prompt is only half of it — without the pending registration the answer would have
     * nowhere to go and would be ignored as unknown text.
     */
    @Test
    void addAsksForTheTaskAndWaitsForIt() {
        CommandReply reply = daily().execute(request(":add"));

        assertThat(reply.text()).isEqualTo("What daily task should I add? Separate several with commas.");
        assertThat(reply.awaitsInput()).isTrue();
        assertThat(reply.inputPlaceholder()).contains("e.g. buy milk, walk the dog");
        assertThat(pendingInput.consume(42L)).contains("/day");
        verifyNoInteractions(taskService);
    }

    @Test
    void addWaitsOnBehalfOfItsOwnTaskType() {
        weekly().execute(new CommandRequest("/week", ":add", 42L));

        assertThat(pendingInput.consume(42L)).contains("/week");
    }

    // --- viewing ----------------------------------------------------------------------------

    @Test
    void viewListsTheStoredTasks() {
        when(taskService.tasksOfType(TaskType.DAILY))
                .thenReturn(List.of(task(1, "buy milk"), task(2, "walk the dog")));

        CommandReply reply = daily().execute(request(":view"));

        assertThat(reply.text()).isEqualTo("Your daily tasks:\n- buy milk\n- walk the dog");
        assertThat(reply.hasButtons()).isFalse();
    }

    @Test
    void viewSaysSoWhenThereAreNone() {
        when(taskService.tasksOfType(TaskType.DAILY)).thenReturn(List.of());

        assertThat(daily().execute(request(":view")).text()).isEqualTo("No daily tasks yet.");
    }

    // --- deleting ---------------------------------------------------------------------------

    @Test
    void deleteOffersOneButtonPerTask() {
        when(taskService.tasksOfType(TaskType.DAILY))
                .thenReturn(List.of(task(7, "buy milk"), task(9, "walk the dog")));

        CommandReply reply = daily().execute(request(":delete"));

        assertThat(reply.text()).isEqualTo("Which daily task should go?");
        assertThat(reply.buttons()).containsExactly(
                new ReplyButton("buy milk", "/day :delete 7"),
                new ReplyButton("walk the dog", "/day :delete 9"));
    }

    @Test
    void deleteRemovesTheChosenTaskAndOffersTheRest() {
        when(taskService.deleteTask(7L, TaskType.DAILY)).thenReturn(true);
        when(taskService.tasksOfType(TaskType.DAILY)).thenReturn(List.of(task(9, "walk the dog")));

        CommandReply reply = daily().execute(request(":delete 7"));

        assertThat(reply.text()).isEqualTo("Deleted. Tap another to delete:");
        assertThat(reply.buttons()).containsExactly(new ReplyButton("walk the dog", "/day :delete 9"));
    }

    @Test
    void deleteReportsAnEmptyListOnceTheLastTaskIsGone() {
        when(taskService.deleteTask(7L, TaskType.DAILY)).thenReturn(true);
        when(taskService.tasksOfType(TaskType.DAILY)).thenReturn(List.of());

        CommandReply reply = daily().execute(request(":delete 7"));

        assertThat(reply.text()).isEqualTo("Deleted. No daily tasks left.");
        assertThat(reply.hasButtons()).isFalse();
    }

    /**
     * An inline button lives on in the chat history long after its task is gone.
     */
    @Test
    void deleteHandlesAButtonThatOutlivedItsTask() {
        when(taskService.deleteTask(7L, TaskType.DAILY)).thenReturn(false);

        assertThat(daily().execute(request(":delete 7")).text()).isEqualTo("That task is already gone.");
    }

    @Test
    void deleteRejectsAnIdThatIsNotANumber() {
        assertThat(daily().execute(request(":delete milk")).text())
                .isEqualTo("That is not a task I can delete.");
        verifyNoInteractions(taskService);
    }

    @Test
    void deleteSaysSoWhenThereIsNothingToDelete() {
        when(taskService.tasksOfType(TaskType.DAILY)).thenReturn(List.of());

        assertThat(daily().execute(request(":delete")).text()).isEqualTo("No daily tasks yet.");
    }

    // --- delete all -------------------------------------------------------------------------

    @Test
    void deleteAllAsksForConfirmationFirst() {
        when(taskService.tasksOfType(TaskType.DAILY))
                .thenReturn(List.of(task(1, "buy milk"), task(2, "walk the dog")));

        CommandReply reply = daily().execute(request(":clear"));

        assertThat(reply.text()).isEqualTo("Delete all 2 daily tasks? This cannot be undone.");
        assertThat(reply.buttons()).containsExactly(
                new ReplyButton("Yes, delete all", "/day :clear-confirmed"),
                new ReplyButton("Cancel", "/day"));
        verify(taskService, never()).deleteAllOfType(TaskType.DAILY);
    }

    @Test
    void deleteAllOnlyDeletesOnceConfirmed() {
        when(taskService.deleteAllOfType(TaskType.DAILY)).thenReturn(3L);

        CommandReply reply = daily().execute(request(":clear-confirmed"));

        assertThat(reply.text()).isEqualTo("Deleted all 3 daily tasks.");
        assertThat(reply.hasButtons()).isFalse();
    }

    @Test
    void deleteAllSaysSoWhenThereIsNothingToDelete() {
        when(taskService.tasksOfType(TaskType.DAILY)).thenReturn(List.of());

        assertThat(daily().execute(request(":clear")).text()).isEqualTo("No daily tasks yet.");
    }

    // --- usage ------------------------------------------------------------------------------

    @Test
    void repliesWithUsageWhenOnlySeparatorsAreGiven() {
        assertThat(daily().execute(request("  ,  , ")).text())
                .isEqualTo("Usage: /day <task>[, <task>, ...]");
        verifyNoInteractions(taskService);
    }
}
